version: "3"

services:

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379"
  #   networks:
  #     - frontend

  # rediscommander:
  #   image: rediscommander/redis-commander
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - frontend
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379

  workspace:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: workspace
    volumes:
      - ./src/workspace:/code/workspace/src/workspace
    env_file:
      - .env
    ports:
      - "6543:6543"
    command:
      - paster
      - serve
      - --reload
      - /code/workspace/development.ini
