version: "3"

services:

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379"
  #   networks:
  #     - frontend

  # rediscommander:
  #   image: rediscommander/redis-commander
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - frontend
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379

  workspace:
    build: .
    image: workspace
    volumes:
      - ./:/code/workspace
    env_file:
      - .env
    ports:
      - "6543:6543"
    networks:
      - frontend


networks:
  frontend:
